### ISSUE TITLE
Installing extra plugin

### ISSUE THREAD

**Issue by johngeorgewright** [codfish/semantic-release-action#168]
If I were to use an extra plugin that this action doesn't use, by default, it does not install it. Is this expected? Feels like this action could install all plugins defined.

**Comment by codfish** [comment]
Can you explain the expected input and result? You want to list 1 or more non-standard plugins that you're using in your config and have the action install those for you right?

can you share what you've been trying so far to see what you'd expect to work? Maybe share a link or some code snippets?

**Comment by MrSwitch** [comment]
> non-standard plugins

I was wondering the same, would it be possible to automatically install even only the [official plugins](https://semantic-release.gitbook.io/semantic-release/extending/plugins-list) which aren't bundled in semantic-release, this would save having to [include them in a projects devDependencies](https://github.com/MrSwitch/tricks/blob/c2145db52303b576951da7be183686a54b94628d/package.json#L67-L69
).

**Comment by codfish** [comment]
@johngeorgewright @MrSwitch hey guys, would you mind testing this before I merge? I don't have a real use case leveraging additional plugins. https://github.com/codfish/semantic-release-action/pull/170

**To summarize**: I've added an `additional_packages` input that will install any npm packages you specify, allowing you to use them in `plugins` or `extends`. Here's an example using semantic's apm extension & plugins:

```yaml
- name: semantic-release
  uses: codfish/semantic-release-action@additional-packages
  with:
    extends: '@semantic-release/apm-config'
    additional_packages: |
      ['@semantic-release/apm@3.0.0', '@semantic-release/git', '@semantic-release/apm-config']
    plugins: |
      ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github', '@semantic-release/apm', '@semantic-release/git']
```

If you have a config in your repo, that will work too, without needing to specify `plugins` or `extends` configuration through inputs.

Be sure to point to this branch when testing: `uses: codfish/semantic-release-action@additional-packages`.
