### ISSUE TITLE
release.config.js is not respected

### ISSUE THREAD

**Issue by niyowski** [codfish/semantic-release-action#199]
I get the following message in the CI:

```
[7:55:03 PM] [semantic-release] › ℹ  Running semantic-release version 22.0.5
...
...
...
[7:55:05 PM] [semantic-release] › ℹ  This test run was triggered on the branch develop, while semantic-release is configured to only publish from main, therefore a new version won’t be published.
```

I want to release in the develop branch therefore my `release.config.js` is:

```
/**
 * @type {import('semantic-release').GlobalConfig}
 */
module.exports = {
  branches: ["develop"],
  // ...
};

```

**Comment by codfish** [comment]
I'll look into it but in the meantime you can do the following:

```yml
- uses: codfish/semantic-release-action
  with:
    branches: ['develop']
```
