### ISSUE TITLE
Update documentation to improve examples

### ISSUE THREAD

**Issue by codfish** [codfish/semantic-release-action#2]
PENDING: Github actions update in second week of september https://github.com/actions/toolkit/issues/96

```yml
steps:
  - uses: actions/checkout@master

  # you'll need to add an `id` in order to access output variables
  - uses: codfish/semantic-release-action@master
    id: semantic
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  - name: docker push version
    if: steps.semantic.outputs.new-release-published == "true"
    run: |
      docker tag $DOCKER_REGISTRY/your-image $DOCKER_REGISTRY/your-image:$TAG
      docker push $DOCKER_REGISTRY/your-image:$TAG
    env:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      TAG: v$RELEASE_VERSION
```
