### ISSUE TITLE
Time to upgrade semantic release?

### ISSUE THREAD

**Issue by dafyddj** [codfish/semantic-release-action#211]
Hi, is it time to upgrade the `semantic-release` package to the latest upstream version?

I had a problem recently with using an ESM packaged preset `conventional-changelog-conventionalcommits`

Thank you

**Comment by codfish** [comment]
can you elaborate on what you were trying to do and what error you saw?

**Comment by dafyddj** [comment]
Configuration of 
```
      - uses: codfish/semantic-release-action@9a999e0cdb207de2c9d9d4276860435727818989 # v3.4.1
        with:
          additional-packages: conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Error
```
[7:40:11 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]: require() of ES Module /github/workspace/node_modules/conventional-changelog-conventionalcommits/src/index.js from /github/workspace/noop.js not supported.
Instead change the require of index.js in /github/workspace/noop.js to a dynamic import() which is available in all CommonJS modules.
    at module.exports (/action/node_modules/import-from/index.js:5:100)
    at default (file:///action/node_modules/@semantic-release/commit-analyzer/lib/load-parser-config.js:25:74)
    at analyzeCommits (file:///action/node_modules/@semantic-release/commit-analyzer/index.js:31:24)
    at validator (file:///action/node_modules/semantic-release/lib/plugins/normalize.js:36:[30](https://github.com/dafyddj/tmp-winrepo-transform/actions/runs/11581228579/job/32241494076#step:5:31))
    at file:///action/node_modules/semantic-release/lib/plugins/pipeline.js:38:42 {
  code: 'ERR_REQUIRE_ESM',
  pluginName: '@semantic-release/commit-analyzer'
}
Error: Error [ERR_REQUIRE_ESM]: require() of ES Module /github/workspace/node_modules/conventional-changelog-conventionalcommits/src/index.js from /github/workspace/noop.js not supported.
Instead change the require of index.js in /github/workspace/noop.js to a dynamic import() which is available in all CommonJS modules.
```

Workaround is to pin to an older version of `conventionalcommits`
`additional-packages: conventional-changelog-conventionalcommits@7.0.2`

No error seen when testing locally with the latest `semantic-release` version.
