### ISSUE TITLE
GitHub url defaults to interactive front-end

### ISSUE THREAD

**Issue by lholota** [codfish/semantic-release-action#98]
Hi, I am using the action in a couple of my repositories and the action started throwing the following error:

```
[10:08:30 AM] [semantic-release] › ✖  An error occurred while running semantic-release: RequestError [HttpError]: Cookies must be enabled to use GitHub.
    at /action/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 403,
...
```

It looks like it's a bug in semantic-release/github. I have filed [an issue](https://github.com/semantic-release/github/issues/271) in their repository. For others, just adding how to mitigate this:

```
      - name: "Determine release version"
        uses: codfish/semantic-release-action@v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_URL: "https://api.github.com" # This overrides the default value
```
